@HostAddress = https://localhost:7056


POST {{HostAddress}}/api/account/register
Content-Type: application/json

{
  "userName": "newuser",
  "password": "NewPass@1234",
  "email": "newuser@example.com"
}


POST {{HostAddress}}/api/account/login
Content-Type: application/json

{
  "userName": "newuser",
  "password": "NewPass@1234"
}


GET {{HostAddress}}/api/account/me
Authorization: Bearer {{your_token}}
